apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secret
  labels:
    app: notification-service
  namespace: default

type: Opaque
data:
  postgres-username: <BASE64_ENCODED_USERNAME>
  postgres-password: <BASE64_ENCODED_PASSWORD>
