apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secret
  labels:
    app: notification-service
  namespace: default

type: Opaque
stringData:
  postgres-username: "notificationdbadmin"
  postgres-password: "P@ssw0rd123!"
